authe/urls.py
from django.urls import path
from authe import views
app_name='authe'
urlpatterns=[
    path('register/',views.registerview,name="register"),
    path('login/',views.loginview,name="login"),
    path('logout/',views.logoutview,name="logout"),
    path('home/',views.homeview,name="home"),
]

matrimony/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('authe/',include('authe.urls')),
    path('pro/',include('prodetail.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

prodetail/urls.py
from django.urls import path
from prodetail import views
app_name="prodetail"
urlpatterns=[
    path('profile/',views.profilehomeview.as_view(),name='profile'),
    path('detail/',views.detailview.as_view(),name='detail'),
    path('education/',views.educationview.as_view(),name='education'),
    path('occupation/',views.occupationview.as_view(),name='occupation'),
    path('family/',views.familyview.as_view(),name='family'),
    path('siblings/',views.siblingsview.as_view(),name='siblings'),
    path('address/',views.addressview.as_view(),name='address'),
    path('profilelink/',views.profilelinkview.as_view(),name='profilelink'),

    path('udetail/<pk>/',views.udetailview.as_view(),name='udetail'),
    path('ueducation/<pk>',views.ueducationview.as_view(),name='ueducation'),
    path('uoccupation/<pk>',views.uoccupationview.as_view(),name='uoccupation'),
    path('ufamily/<pk>',views.ufamilyview.as_view(),name='ufamily'),
    path('usiblings/<pk>',views.usiblingsview.as_view(),name='usiblings'),
    path('uaddress/<pk>',views.uaddressview.as_view(),name='uaddress'),
    path('uprofilelink/<pk>',views.uprofilelinkview.as_view(),name='uprofilelink'),
   
    ]

authe/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class registermodel(User):
    phone=models.BigIntegerField(unique=True)
    age=models.IntegerField()
    choices=[['Male','MALE'],['Female','FEMALE']]
    gender=models.CharField(max_length=10,choices=choices)
    dob=models.DateField()









   

authe/forms.py
from django import forms
from authe.models import registermodel
from django.contrib.auth.hashers import make_password
class registerform(forms.ModelForm):
    class Meta:
        model=registermodel
        fields=['username','first_name','last_name','email','phone','age','gender','dob','password']
        widgets={'password':forms.PasswordInput}
    repassword=forms.CharField(widget=forms.PasswordInput)
    def save(self,commit=True):
        user=super().save(commit=False)
        user.password=make_password(self.cleaned_data['password'])
        if commit==True:
            user.save()
        return user
    def clean(self):
        pas=self.cleaned_data['password']
        rpas=self.cleaned_data['repassword']
        if not(pas == rpas):
            raise forms.ValidationError('password and repassword should be same')

        age=self.cleaned_data['age']
        if not(16<=age<=65):
            raise forms.ValidationError('age should be min 16 years max 65 years')
        
        if not(3<=len(pas)<=10):
            raise forms.ValidationError('password should be min 3 characters max 10 characters')
        


class loginform(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

authe/views.py
from contextlib import redirect_stderr
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.views.generic import CreateView
from authe.models import registermodel
from authe.forms import registerform,loginform
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

def registerview(request):
    form=registerform()
    if request.method=='POST':
        form=registerform(request.POST)
        if form.is_valid():
            form.save()
            email=form.cleaned_data['email']
            user=form.cleaned_data['username']
            subject='welcome to spiders matrimony '
            message=f'Hi Mr/Mrs.. {user.title()}\n select your companion'
            email_from= settings.EMAIL_HOST_USER
            rep=[email,]
            send_mail(message=message, subject=subject, from_email=email_from, recipient_list=rep)
            messages.success(request,'registration is success')
            return redirect('/authe/login/')
        else:
            messages.error(request,'registration is failed')
            
    return render(request,'register.html',{'form':form})

def loginview(request):
    form=loginform()
    if request.method=='POST':
        form=loginform(request.POST)
        if form.is_valid():
            user=authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password'])
            if user is not None:
                login(request,user)
                messages.success(request,'login is success')
                return redirect('/authe/home/')
            else:
                messages.error(request,'login is failed')
    return render(request,'login.html',{'form':form})

@login_required(login_url='/authe/login/')
def logoutview(request):
    logout(request)
    messages.success(request,'logout is success')
    return redirect('/authe/login/')

@login_required(login_url='/authe/login/')
def homeview(request):
    return render(request,'home.html')
'''
class registerview(CreateView):
    template_name='register.html'
    model=registermodel
    context_object_name='form'
    fields=['username','first_name','last_name','email','phone','age','gender','dob','password']
    form_class=registerform
    success_url='/admin/'

'''

authe/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if messages%}
    {%for i in messages%}
    <h5>{{i}}</h5>
    {%endfor%}
    {%endif%}
    <h1> this is home page</h1>
    {%if user.is_authenticated%}
        <h1> {{user.id}} {{user.username|upper}} {{user.email}}</h1>
    <a href="{%url 'prodetail:profile'%}" ><button>profile</button></a>

    <a href="{%url 'authe:logout' %}"><button>logout</button></a>

    {%endif%}
</body>
</html>

authe/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if messages%}
    {%for i in messages%}
    <h5>{{i}}</h5>
    {%endfor%}
    {%endif%}
    
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="login">
</body>
</html>

!

authe/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="register">
</body>
</html>

!